package ru.strange.client.localization;

import ru.strange.client.ui.clickgui.localization.GuiLanguage;
import ru.strange.client.ui.clickgui.localization.GuiLocalization;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public final class ModLocalization {
    private static final Map<String, String> RU = new HashMap<>();
    private static final Map<String, String> EN = new HashMap<>();
    private static final Map<String, String> RU_RAW = new HashMap<>();
    private static final Map<String, String> EN_RAW = new HashMap<>();

    static {
        register("common.empty", "Пусто", "Empty");
        register("common.press", "Нажми", "Press");
        register("common.press_key", "Нажмите кнопку", "Press a key");
        register("common.select", "Выберите", "Select");
        register("hud.seconds", "%s сек", "%s sec");
        register("hud.move_hint", "ALT + ЛКМ - двигать", "ALT + LMB - move");
        register("hud.target.preview", "Странный тип", "Practice target");
        register("friend.added.prefix", "Друг - ", "Friend - ");
        register("friend.added.suffix", " добавлен :)", " added :)");
        register("friend.removed.suffix", " удален :(", " removed :(");
        register("pause.apply_skin", "Поставить скин", "Apply skin");
        register("pause.reset_skin", "Сбросить скин", "Reset skin");
        register("server.prefix", "Правила сервера", "Server rules");
        register("server.module.available", "%s снова доступен", "%s is available again");
        register("server.module.disabled", "%s отключен профилем %s", "%s was disabled by profile %s");
        register("server.module.hidden", "%s скрыт профилем %s", "%s is hidden by profile %s");
        register("command.error.execution", "Ошибка выполнения команды: %s", "Command execution error: %s");
        register("command.cfg.name_hint", "Разрешены только буквы, цифры, '-' и '_'.", "Only letters, digits, '-' and '_' are allowed.");
        register("command.cfg.unknown_action", "§cНеизвестное действие: §e%s", "§cUnknown action: §e%s");
        register("command.cfg.saved", "§aКонфиг §e%s§a успешно сохранен.", "§aConfig §e%s§a saved successfully.");
        register("command.cfg.save_failed", "§cНе удалось сохранить конфиг §e%s§c.", "§cFailed to save config §e%s§c.");
        register("command.cfg.loaded", "§aКонфиг §e%s§a успешно загружен.", "§aConfig §e%s§a loaded successfully.");
        register("command.cfg.load_failed", "§cКонфиг §e%s§c не найден или поврежден.", "§cConfig §e%s§c was not found or is corrupted.");
        register("command.cfg.deleted", "§aКонфиг §e%s§a удален.", "§aConfig §e%s§a deleted.");
        register("command.cfg.delete_failed", "§cНе удалось удалить конфиг §e%s§c.", "§cFailed to delete config §e%s§c.");
        register("command.cfg.none_saved", "§eСохраненных конфигов нет.", "§eNo saved configs.");
        register("command.cfg.saved_list", "§eСохраненные конфиги §7(%s)§e:", "§eSaved configs §7(%s)§e:");
        register("command.cfg.usage_action", "§cИспользование: §7.cfg %s <название>", "§cUsage: §7.cfg %s <name>");
        register("command.cfg.invalid_name", "§cНекорректное имя конфига.", "§cInvalid config name.");
        register("command.cfg.usage_title", "§eИспользование:", "§eUsage:");
        register("command.cfg.usage_save", "§7.cfg save <название> §f- сохранить конфиг", "§7.cfg save <name> §f- save config");
        register("command.cfg.usage_load", "§7.cfg load <название> §f- загрузить конфиг", "§7.cfg load <name> §f- load config");
        register("command.cfg.usage_delete", "§7.cfg delete <название> §f- удалить конфиг", "§7.cfg delete <name> §f- delete config");
        register("command.cfg.usage_list", "§7.cfg list §f- список конфигов", "§7.cfg list §f- list configs");

        registerRaw("Custom Crosshair", "Кастомный прицел", "Custom Crosshair");
        registerRaw("кастомный прицел с динамикой и combat-индикацией", "кастомный прицел с динамикой и боевой индикацией", "custom crosshair with dynamic combat feedback");
        registerRaw("Режим", "Режим", "Mode");
        registerRaw("Орбиты", "Орбиты", "Orbits");
        registerRaw("Круг", "Круг", "Circle");
        registerRaw("Размер", "Размер", "Size");
        registerRaw("Толщина", "Толщина", "Thickness");
        registerRaw("Отступ", "Отступ", "Gap");
        registerRaw("Кол-во орб", "Кол-во орб", "Orbit Count");
        registerRaw("Динамика КД", "Динамика КД", "Cooldown Dynamics");
        registerRaw("Основной цвет", "Основной цвет", "Base Color");
        registerRaw("Цвет наводки", "Цвет наводки", "Target Color");
        registerRaw("Цвет крита", "Цвет крита", "Critical Color");
        registerRaw("Цвет хита", "Цвет хита", "Hit Color");
        registerRaw("Кастомизировать руки", "Кастомизировать руки", "Customize Hands");
        registerRaw("Кастомизация анимации руки", "Кастомизация анимации руки", "Hand animation customization");
        registerRaw("Анимация", "Анимация", "Animation");
        registerRaw("Smooth", "Плавная", "Smooth");
        registerRaw("Swipe", "Свайп", "Swipe");
        registerRaw("Swipe back", "Обратный свайп", "Swipe back");
        registerRaw("SwipeD", "Диагональный свайп", "SwipeD");
        registerRaw("Down", "Вниз", "Down");
        registerRaw("Spin", "Спин", "Spin");
        registerRaw("Off", "Выкл", "Off");
        registerRaw("Скорость анимации", "Скорость анимации", "Animation Speed");
        registerRaw("Размер анимации", "Размер анимации", "Animation Size");
        registerRaw("Модель Руки", "Модель руки", "Hand Model");
        registerRaw("X правая", "X правая", "Right X");
        registerRaw("Y правая", "Y правая", "Right Y");
        registerRaw("Z правая", "Z правая", "Right Z");
        registerRaw("X левая", "X левая", "Left X");
        registerRaw("Y левая", "Y левая", "Left Y");
        registerRaw("Z левая", "Z левая", "Left Z");
        registerRaw("Водяной знак", "Водяной знак", "Watermark");
        registerRaw("Ватермарка", "Ватермарка", "Watermark Bar");
        registerRaw("Ник", "Ник", "Name");
        registerRaw("ФПС", "ФПС", "FPS");
        registerRaw("Пинг", "Пинг", "Ping");
        registerRaw("Время", "Время", "Time");
        registerRaw("Сервер", "Сервер", "Server");
        registerRaw("Элементы", "Элементы", "Elements");
        registerRaw("Модули", "Модули", "Modules");
        registerRaw("Таргет худ", "Таргет худ", "Target HUD");
        registerRaw("Инвентарь", "Инвентарь", "Inventory");
        registerRaw("Потионы", "Потионы", "Potions");
        registerRaw("Кулдауны", "Кулдауны", "Cooldowns");
        registerRaw("Координаты", "Координаты", "Coords");
        registerRaw("Редактирование", "Редактирование", "Edit Mode");
        registerRaw("Аспект ратион", "Аспект ратион", "Aspect Ratio");
        registerRaw("Соотношение экрана", "Соотношение экрана", "Aspect Ratio");
        registerRaw("16:9", "16:9", "16:9");
        registerRaw("4:3", "4:3", "4:3");
        registerRaw("1:1", "1:1", "1:1");
        registerRaw("16:10", "16:10", "16:10");
        registerRaw("21:9", "21:9", "21:9");
        registerRaw("32:9", "32:9", "32:9");
        registerRaw("5:4", "5:4", "5:4");
        registerRaw("2:1", "2:1", "2:1");
        registerRaw("Кастомное", "Кастомное", "Custom");
        registerRaw("Кастомое значние", "Кастомное значение", "Custom Value");
        registerRaw("АукХелпер", "АукХелпер", "Auction Helper");
        registerRaw("Команда /ah search с предметом в руке", "Команда /ah search с предметом в руке", "Runs /ah search with the held item");
        registerRaw("Бинд", "Бинд", "Bind");
        registerRaw("Кастомный туман", "Кастомный туман", "Custom Fog");
        registerRaw("Настраиваемый цвет тумана", "Настраиваемый цвет тумана", "Configurable fog color");
        registerRaw("Гамма", "Гамма", "Gamma");
        registerRaw("Ночное зрение", "Ночное зрение", "Night Vision");
        registerRaw("Цвет тумана", "Цвет тумана", "Fog Color");
        registerRaw("Module Sounds", "Звуки мода", "Module Sounds");
        registerRaw("toggle and utility sound settings", "настройки звуков модулей и утилит", "module and utility sound settings");
        registerRaw("Звуки модулей", "Звуки модулей", "Module Sounds");
        registerRaw("Профиль", "Профиль", "Profile");
        registerRaw("Function", "Function", "Function");
        registerRaw("Classic", "Classic", "Classic");
        registerRaw("Громкость", "Громкость", "Volume");
        registerRaw("Физика предметов", "Физика предметов", "Item Physics");
        registerRaw("Размер предмета", "Размер предмета", "Item Size");
        registerRaw("Без рендера", "Без рендера", "No Render");
        registerRaw("Настройки", "Настройки", "Settings");
        registerRaw("Убрать огонь", "Убрать огонь", "Hide Fire");
        registerRaw("Убрать тряску", "Убрать тряску", "Hide Shake");
        registerRaw("Убрать тыкву", "Убрать тыкву", "Hide Pumpkin");
        registerRaw("Убрать портал", "Убрать портал", "Hide Portal");
        registerRaw("Убрать скорборд", "Убрать скорборд", "Hide Scoreboard");
        registerRaw("Оптимизация", "Оптимизация", "Optimization");
        registerRaw("Автоматическая оптимизация настроек графики", "Автоматическая оптимизация настроек графики", "Automatic graphics optimization");
        registerRaw("Партиклы", "Партиклы", "Particles");
        registerRaw("Облака", "Облака", "Clouds");
        registerRaw("Энтити", "Энтити", "Entities");
        registerRaw("Дальность чанков", "Дальность чанков", "Chunk Distance");
        registerRaw("Симуляция", "Симуляция", "Simulation");
        registerRaw("Тени энтити", "Тени энтити", "Entity Shadows");
        registerRaw("VSync", "VSync", "VSync");
        registerRaw("Screen Filters", "Фильтры экрана", "Screen Filters");
        registerRaw("пост-фильтры экрана", "пост-фильтры экрана", "screen post-filters");
        registerRaw("Насыщенность", "Насыщенность", "Saturation");
        registerRaw("Экспозиция", "Экспозиция", "Exposure");
        registerRaw("Контраст", "Контраст", "Contrast");
        registerRaw("Яркость", "Яркость", "Brightness");
        registerRaw("Виньетка", "Виньетка", "Vignette");
        registerRaw("Зерно", "Зерно", "Grain");
        registerRaw("Оттенок", "Оттенок", "Tint");
        registerRaw("Сила оттенка", "Сила оттенка", "Tint Strength");
        registerRaw("Время суток", "Время суток", "Time Set");
        registerRaw("Поставить свое время суток", "Поставить свое время суток", "Set your own time of day");
        registerRaw("Ночь", "Ночь", "Night");
        registerRaw("День", "День", "Day");
        registerRaw("Закат", "Закат", "Sunset");
        registerRaw("Рассвет", "Рассвет", "Sunrise");
        registerRaw("Полночь", "Полночь", "Midnight");
        registerRaw("Полдень", "Полдень", "Noon");
        registerRaw("Боксы", "Боксы", "Boxes");
        registerRaw("боксы и глоу-обводка по целям", "боксы и глоу-обводка по целям", "boxes and glow outline for targets");
        registerRaw("Оба", "Оба", "Both");
        registerRaw("Бокс", "Бокс", "Box");
        registerRaw("Глоу", "Глоу", "Glow");
        registerRaw("Кого отображать", "Кого отображать", "Targets");
        registerRaw("Игроки", "Игроки", "Players");
        registerRaw("Мобы", "Мобы", "Mobs");
        registerRaw("HitColor", "Цвет удара", "Hit Color");
        registerRaw("Цвет удара", "Цвет удара", "Hit Color");
        registerRaw("Дистанция", "Дистанция", "Range");
        registerRaw("Размер глоу", "Размер глоу", "Glow Size");
        registerRaw("Цвет 1", "Цвет 1", "Color 1");
        registerRaw("Цвет 2", "Цвет 2", "Color 2");
        registerRaw("FakeHitboxes", "Фейковые хитбоксы", "Fake Hitboxes");
        registerRaw("фейковое отображение увеличенных хитбоксов", "фейковое отображение увеличенных хитбоксов", "fake rendering of enlarged hitboxes");
        registerRaw("Режим", "Режим", "Mode");
        registerRaw("Под прицелом", "Под прицелом", "Targeted");
        registerRaw("Расширение", "Расширение", "Expand");
        registerRaw("Заливка", "Заливка", "Fill");
        registerRaw("Shader Hand", "Шейдерная рука", "Shader Hand");
        registerRaw("Transparent and shader-driven hand rendering", "прозрачный рендер руки с шейдерными режимами", "transparent hand rendering with shader-driven modes");
        registerRaw("Mode", "Режим", "Mode");
        registerRaw("Glass", "Стекло", "Glass");
        registerRaw("Shader", "Шейдер", "Shader");
        registerRaw("Shader Theme", "Тема шейдера", "Shader Theme");
        registerRaw("Blur Radius", "Радиус блюра", "Blur Radius");
        registerRaw("Blur Iterations", "Проходы блюра", "Blur Iterations");
        registerRaw("Saturation", "Насыщенность", "Saturation");
        registerRaw("Tint", "Оттенок", "Tint");
        registerRaw("Tint Color", "Цвет оттенка", "Tint Color");
        registerRaw("Цвет оттенка", "Цвет оттенка", "Tint Color");
        registerRaw("Tint Strength", "Сила оттенка", "Tint Strength");
        registerRaw("Edge Glow", "Свечение края", "Edge Glow");
        registerRaw("Edge Glow Strength", "Сила свечения края", "Edge Glow Strength");
        registerRaw("Hand Glow", "Свечение руки", "Hand Glow");
        registerRaw("Hand Glow Color", "Цвет свечения руки", "Hand Glow Color");
        registerRaw("Hand Glow Power", "Сила свечения руки", "Hand Glow Power");
        registerRaw("Star Density", "Плотность звезд", "Star Density");
        registerRaw("Star Speed", "Скорость звезд", "Star Speed");
        registerRaw("Shader Intensity", "Интенсивность шейдера", "Shader Intensity");
        registerRaw("Shader Color", "Цвет шейдера", "Shader Color");
        registerRaw("Shader Edge Glow", "Свечение края шейдера", "Shader Edge Glow");
        registerRaw("Shader Edge Strength", "Сила края шейдера", "Shader Edge Strength");
        registerRaw("Pulse Alpha", "Альфа Pulse", "Pulse Alpha");
        registerRaw("Pulse Effect Only", "Только Pulse-эффект", "Pulse Effect Only");
        registerRaw("Китайская шляпа", "Китайская шляпа", "Chinese Hat");
        registerRaw("Цвет", "Цвет", "Color");
        registerRaw("Один цвет", "Один цвет", "Single Color");
        registerRaw("Два цвета", "Два цвета", "Two Colors");
        registerRaw("Альфа", "Альфа", "Alpha");
        registerRaw("Сегменты", "Сегменты", "Segments");
        registerRaw("Высота", "Высота", "Height");
        registerRaw("Ширина", "Ширина", "Width");
        registerRaw("Контур", "Контур", "Outline");
        registerRaw("Толщина контура", "Толщина контура", "Outline Width");
        registerRaw("Вращение", "Вращение", "Rotation");
        registerRaw("Скорость вращения", "Скорость вращения", "Rotation Speed");
        registerRaw("Хит бабл", "Хит бабл", "Hit Bubble");
        registerRaw("Эффект кольца при ударе по цели", "Эффект кольца при ударе по цели", "Ring effect on hit");
        registerRaw("Текстура", "Текстура", "Texture");
        registerRaw("Bubble1", "Bubble1", "Bubble1");
        registerRaw("Bubble2", "Bubble2", "Bubble2");
        registerRaw("JumpCircle", "Круги прыжка", "JumpCircle");
        registerRaw("Круги и world-scan эффекты", "Круги и world-scan эффекты", "circle and world-scan effects");
        registerRaw("Эффект", "Эффект", "Effect");
        registerRaw("Скан", "Скан", "Scan");
        registerRaw("Акцент", "Акцент", "Accent");
        registerRaw("Триггеры", "Триггеры", "Triggers");
        registerRaw("Прыжок", "Прыжок", "Jump");
        registerRaw("Тотем", "Тотем", "Totem");
        registerRaw("Убийство", "Убийство", "Kill");
        registerRaw("Радиус скана", "Радиус скана", "Scan Radius");
        registerRaw("Ширина скана", "Ширина скана", "Scan Width");
        registerRaw("Длительность", "Длительность", "Duration");
        registerRaw("Волна", "Волна", "Wave");
        registerRaw("Kill Effect", "Эффект убийства", "Kill Effect");
        registerRaw("эффекты на убийство и tot em pop", "эффекты на убийство и тотем-поп", "effects for kills and totem pops");
        registerRaw("Комбо", "Комбо", "Combo");
        registerRaw("Нет", "Нет", "None");
        registerRaw("Молния", "Молния", "Lightning");
        registerRaw("Звезда", "Звезда", "Star");
        registerRaw("Вспышка", "Вспышка", "Flash");
        registerRaw("Частицы", "Частицы", "Particles");
        registerRaw("Толщина молнии", "Толщина молнии", "Lightning Width");
        registerRaw("Частицы Игрока", "Частицы игрока", "Player Particles");
        registerRaw("Частицы при атаке и броске", "Частицы при атаке и броске", "particles on hit and throw");
        registerRaw("Атака", "Атака", "Attack");
        registerRaw("Бросок", "Бросок", "Throw");
        registerRaw("Тип частиц", "Тип частиц", "Particle Type");
        registerRaw("Bloom", "Блум", "Bloom");
        registerRaw("Star", "Звезда", "Star");
        registerRaw("Snow", "Снег", "Snow");
        registerRaw("Heart", "Сердце", "Heart");
        registerRaw("Dollar", "Доллар", "Dollar");
        registerRaw("Triangle", "Треугольник", "Triangle");
        registerRaw("Sakura", "Сакура", "Sakura");
        registerRaw("Genshin", "Genshin", "Genshin");
        registerRaw("Rhombus", "Ромб", "Rhombus");
        registerRaw("Таргет рендер", "Таргет рендер", "Target ESP");
        registerRaw("Рендер текущей цели", "Рендер текущей цели", "Renders the current target");
        registerRaw("Картинка", "Картинка", "Image");
        registerRaw("Призраки", "Призраки", "Ghosts");
        registerRaw("Кубики", "Кубики", "Cubes");
        registerRaw("Режим призраков", "Режим призраков", "Ghost Mode");
        registerRaw("Обычный", "Обычный", "Default");
        registerRaw("Новый", "Новый", "New");
        registerRaw("Старый", "Старый", "Old");
        registerRaw("Режим кубиков", "Режим кубиков", "Cube Mode");
        registerRaw("Размер картинки", "Размер картинки", "Image Size");
        registerRaw("Размер кубиков", "Размер кубиков", "Cube Size");
        registerRaw("Количество кубиков", "Количество кубиков", "Cube Count");
        registerRaw("Скорость спавна", "Скорость спавна", "Spawn Rate");
        registerRaw("Ghost Count", "Кол-во призраков", "Ghost Count");
        registerRaw("Ghost Radius", "Радиус призраков", "Ghost Radius");
        registerRaw("Ghost Speed", "Скорость призраков", "Ghost Speed");
        registerRaw("Ghost Path", "Траектория призраков", "Ghost Path");
        registerRaw("Шлейф", "Шлейф", "Trails");
        registerRaw("Шлейф частиц за игроком", "Шлейф частиц за игроком", "particle trail behind the player");
        registerRaw("Режим цвета", "Режим цвета", "Color Mode");
        registerRaw("Client", "Client", "Client");
        registerRaw("Random", "Случайный", "Random");
        registerRaw("Astolfo", "Astolfo", "Astolfo");
        registerRaw("Длина", "Длина", "Length");
        registerRaw("Сглаживание", "Сглаживание", "Smoothing");
        registerRaw("Свечение", "Свечение", "Glow");
        registerRaw("От первого лица", "От первого лица", "First Person");
        registerRaw("Авто респавн", "Авто респавн", "Auto Respawn");
        registerRaw("Автоматический респавн с показом координат смерти", "Автоматический респавн с показом координат смерти", "automatic respawn with death coordinates");
        registerRaw("Координаты смерти", "Координаты смерти", "Death Coordinates");
        registerRaw("Авто бег", "Авто бег", "Auto Run");
        registerRaw("Автоматический бег", "Автоматический бег", "Automatic sprinting");
        registerRaw("Авто Свап", "Авто свап", "Auto Swap");
        registerRaw("Свап с", "Свап с", "Swap From");
        registerRaw("Сфера", "Сфера", "Crystal");
        registerRaw("Свап на", "Свап на", "Swap To");
        registerRaw("Кнопка свапа", "Кнопка свапа", "Swap Key");
        registerRaw("Задержка", "Задержка", "Delay");
        registerRaw("Чат Хелпер", "Чат хелпер", "Chat Helper");
        registerRaw("Анти-спам и сохранение истории чата", "Анти-спам и сохранение истории чата", "anti-spam and chat history");
        registerRaw("Анти-спам", "Анти-спам", "Anti-Spam");
        registerRaw("Сохранять историю", "Сохранять историю", "Keep History");
        registerRaw("Фейк игрок", "Фейк игрок", "Fake Player");
        registerRaw("Спавнит клиентского фейк-игрока для тренировки PvP", "Спавнит клиентского фейк-игрока для тренировки PvP", "spawns a client-side fake player for PvP practice");
        registerRaw("Бесконечный тотем", "Бесконечный тотем", "Infinite Totem");
        registerRaw("Копировать броню", "Копировать броню", "Copy Armor");
        registerRaw("Фри Лук", "Фри лук", "Free Look");
        registerRaw("Кнопка", "Кнопка", "Key");
        registerRaw("Авто F5", "Авто F5", "Auto F5");
        registerRaw("ФТХелпер", "ФТХелпер", "Throw Helper");
        registerRaw("Помощник для бросков и дистанций", "Помощник для бросков и дистанций", "helper for throws and distances");
        registerRaw("Проекция Зелия", "Проекция зелья", "Potion Projection");
        registerRaw("Проекция Снежка", "Проекция снежка", "Snowball Projection");
        registerRaw("Проекция Дезориентация", "Проекция дезориентации", "Disorientation Projection");
        registerRaw("Проекция Явной пыли", "Проекция явной пыли", "Visible Dust Projection");
        registerRaw("Проекция Огненый смерчь", "Проекция огненного смерча", "Fire Tornado Projection");
        registerRaw("Хит Саунд", "Хит саунд", "Hit Sound");
        registerRaw("воспроизводит звук при подтвержденном ударе", "воспроизводит звук при подтвержденном ударе", "plays a sound on confirmed hit");
        registerRaw("Звук", "Звук", "Sound");
        registerRaw("Случайный", "Случайный", "Random");
        registerRaw("Кастом", "Кастом", "Custom");
        registerRaw("Hit 1", "Hit 1", "Hit 1");
        registerRaw("Hit 2", "Hit 2", "Hit 2");
        registerRaw("Hit 3", "Hit 3", "Hit 3");
        registerRaw("Hit 4", "Hit 4", "Hit 4");
        registerRaw("Hit 5", "Hit 5", "Hit 5");
        registerRaw("Триггер", "Триггер", "Trigger");
        registerRaw("Любой удар", "Любой удар", "Any Hit");
        registerRaw("Только крит", "Только крит", "Critical Only");
        registerRaw("Папка звуков", "Папка звуков", "Sounds Folder");
        registerRaw("Открыть", "Открыть", "Open");
        registerRaw("Обновить список", "Обновить список", "Refresh List");
        registerRaw("Обновить", "Обновить", "Refresh");
        registerRaw("Выбрать звук", "Выбрать звук", "Select Sound");
        registerRaw("custom.wav", "custom.wav", "custom.wav");
        registerRaw("Громкость", "Громкость", "Volume");
        registerRaw("Прокрутка предметов", "Прокрутка предметов", "Item Scroller");
        registerRaw("Скорость", "Скорость", "Speed");
        registerRaw("Добавить друга", "Добавить друга", "Add Friend");
        registerRaw("Добавляем своего друга по кнопке", "Добавляем своего друга по кнопке", "adds or removes a friend by key");
        registerRaw("ПвП Хелпер", "ПвП хелпер", "PvP Helper");
        registerRaw("Быстрый свап элитры/нагрудника и переключение на пёрл", "Быстрый свап элитры/нагрудника и переключение на пёрл", "quick elytra/chestplate swap and pearl switch");
        registerRaw("Бинд на пёрл", "Бинд на пёрл", "Pearl Bind");
        registerRaw("Бинд на элитру", "Бинд на элитру", "Elytra Bind");
        registerRaw("Шифт тап", "Шифт тап", "Shift Tap");
        registerRaw("Автоматическое приседание при атаке для крита", "Автоматическое приседание при атаке для крита", "auto sneak on attack for criticals");
        registerRaw("Тики шифта", "Тики шифта", "Sneak Ticks");
        registerRaw("Авто подключение (ST)", "Авто подключение (ST)", "Auto Join (ST)");
        registerRaw("Тейп маус", "Тейп маус", "Tape Mouse");
        registerRaw("более аккуратный автоклик по цели", "более аккуратный автоклик по цели", "safer target-based auto clicker");
        registerRaw("Только с ЛКМ", "Только с ЛКМ", "Only With LMB");
        registerRaw("Джиттер", "Джиттер", "Jitter");
        registerRaw("Синхрон с КД", "Синхрон с КД", "Sync With Cooldown");
        registerRaw("Мин. КД", "Мин. КД", "Min Cooldown");
        registerRaw("Обводка блока", "Обводка блока", "Block Outline");
        registerRaw("Красивые режимы обводки блока под прицелом", "Красивые режимы обводки блока под прицелом", "stylized block outline modes for the targeted block");
        registerRaw("Хитбокс", "Хитбокс", "Hitbox");
        registerRaw("Космос", "Космос", "Cosmos");
        registerRaw("Космос 2", "Космос 2", "Cosmos 2");
        registerRaw("Аврора", "Аврора", "Aurora");
        registerRaw("Лава", "Лава", "Lava");
        registerRaw("Океан", "Океан", "Ocean");
        registerRaw("Матрица", "Матрица", "Matrix");
        registerRaw("Токсин", "Токсин", "Toxin");
        registerRaw("Гроза", "Гроза", "Thunder");
        registerRaw("Кристалл", "Кристалл", "Crystal");
        registerRaw("Закат", "Закат", "Sunset");
        registerRaw("Янтарь", "Янтарь", "Amber");
        registerRaw("Неон", "Неон", "Neon");
        registerRaw("Пустота", "Пустота", "Void");
        registerRaw("Сакура", "Сакура", "Sakura");
        registerRaw("Паутина", "Паутина", "Web");
        registerRaw("Ледник", "Ледник", "Glacier");
        registerRaw("Солярис", "Солярис", "Solaris");
        registerRaw("Фрактал", "Фрактал", "Fractal");
        registerRaw("Затмение", "Затмение", "Eclipse");
        registerRaw("Схема", "Схема", "Circuit");
        registerRaw("Коралл", "Коралл", "Coral");
        registerRaw("Призма", "Призма", "Prism");
        registerRaw("Муссон", "Муссон", "Monsoon");
        registerRaw("Блум", "Блум", "Bloom");
        registerRaw("Небула", "Небула", "Nebula");
        registerRaw("Старфилд", "Старфилд", "Starfield");
        registerRaw("Плазма", "Плазма", "Plasma");
        registerRaw("Цвет хитбокса", "Цвет хитбокса", "Hitbox Color");
        registerRaw("Цвет шейдера", "Цвет шейдера", "Shader Color");
        registerRaw("Цвет паутины", "Цвет паутины", "Web Color");
        registerRaw("Цвет плазмы", "Цвет плазмы", "Plasma Color");
        registerRaw("Прозрачность", "Прозрачность", "Opacity");
        registerRaw("Яркость линии", "Яркость линии", "Line Brightness");
        registerRaw("Плотность", "Плотность", "Density");
        registerRaw("Тема шейдера", "Тема шейдера", "Shader Theme");
        registerRaw("Сгустки", "Сгустки", "Blobs");
        registerRaw("Прыг кубики", "Прыг кубики", "Jump Cubes");
        registerRaw("Рендерит небольшие кубики вокруг игроков", "Рендерит небольшие кубики вокруг игроков", "renders small cubes around players");
        registerRaw("Количество", "Количество", "Count");
        registerRaw("Прыжки", "Прыжки", "Jumps");
        registerRaw("Все сущности", "Все сущности", "All Entities");
        registerRaw("RGB", "RGB", "RGB");
        registerRaw("Летающие кубики жоско", "Летающие кубики жоско", "aggressive floating cubes");
        registerRaw("Кол кубиков", "Кол-во кубиков", "Cube Count");
        registerRaw("Частицы Мира", "Частицы мира", "World Particles");
        registerRaw("Частицы в мире", "Частицы в мире", "particles in the world");
        registerRaw("Нажмите кнопку", "Нажмите кнопку", "Press a key");
        registerRaw("Нажми", "Нажми", "Press");
        registerRaw("Выберите", "Выберите", "Select");
        registerRaw("Пусто", "Пусто", "Empty");
        registerRaw("FREE", "БЕСПЛАТНО", "FREE");
        registerRaw("singleplayer", "Одиночная игра", "Singleplayer");
        registerRaw("unknown", "Неизвестно", "Unknown");
        registerRaw("Pulse • Nebula", "Pulse • Туманность", "Pulse • Nebula");
        registerRaw("Pulse • Starfield", "Pulse • Звездное поле", "Pulse • Starfield");
        registerRaw("Pulse • Cobweb", "Pulse • Паутина", "Pulse • Cobweb");
        registerRaw("Pulse • Plasma", "Pulse • Плазма", "Pulse • Plasma");
        registerRaw("Item Overrides", "Профили предметов", "Item Overrides");
        registerRaw("Item Shaders", "Шейдеры предметов", "Item Shaders");
        registerRaw("editor for per-item hand shader profiles", "редактор отдельных шейдерных профилей для предметов в руках", "editor for per-item hand shader profiles");
        registerRaw("Profile Editor", "Редактор профилей", "Profile Editor");
        registerRaw("Item Shader Editor", "Редактор шейдеров предметов", "Item Shader Editor");
        registerRaw("Item Profiles UI", "Профили предметов", "Item Profiles UI");
        registerRaw("Open", "Открыть", "Open");
        registerRaw("Edit", "Изменить", "Edit");
        registerRaw("Shader Theme", "Тема шейдера", "Shader Theme");
        registerRaw("Shader Colors", "Цвета шейдера", "Shader Colors");
        registerRaw("Shader", "Шейдер", "Shader");
        registerRaw("Circle Radius", "Радиус круга", "Circle Radius");
        registerRaw("Friend Shader", "Шейдер друзей", "Friend Shader");
        registerRaw("Friend Shader Theme", "Тема шейдера друзей", "Friend Shader Theme");
        registerRaw("Style", "Стиль", "Style");
        registerRaw("Default", "Обычный", "Default");
        registerRaw("kill and totem pop visuals with lightning, particles and shockwaves", "эффекты убийства и тотема с молниями, партиклами и ударными волнами", "kill and totem pop visuals with lightning, particles and shockwaves");
        registerRaw("Шоквейв", "Шоквейв", "Shockwave");
        registerRaw("Ванильные", "Ванильные", "Vanilla");
        registerRaw("Стиль молнии", "Стиль молнии", "Lightning Style");
        registerRaw("Кастомная", "Кастомная", "Custom");
        registerRaw("Ванильная", "Ванильная", "Vanilla");
        registerRaw("Ванильные частицы", "Ванильные частицы", "Vanilla Particles");
        registerRaw("Радиус волны", "Радиус волны", "Shockwave Radius");
        registerRaw("Ширина волны", "Ширина волны", "Shockwave Width");
        registerRaw("Heart", "Сердце", "Heart");
        registerRaw("Snow", "Снег", "Snow");
        registerRaw("Dollar", "Доллар", "Dollar");
        registerRaw("Triangle", "Треугольник", "Triangle");
        registerRaw("Sakura", "Сакура", "Sakura");
        registerRaw("Gemini", "Гемини", "Gemini");
        registerRaw("Sims", "Симс", "Sims");
        registerRaw("Totem", "Тотем", "Totem");
        registerRaw("End Rod", "Энд-стержень", "End Rod");
        registerRaw("Electric Spark", "Электрическая искра", "Electric Spark");
        registerRaw("Soul Fire", "Огонь души", "Soul Fire");
        registerRaw("Glow", "Свечение", "Glow");
        registerRaw("Damage Indicator", "Индикатор урона", "Damage Indicator");
        registerRaw("Crit", "Крит", "Crit");
        registerRaw("Watermark", "Водяной знак", "Watermark");
        registerRaw("Modules", "Модули", "Modules");
        registerRaw("Target", "Цель", "Target");
        registerRaw("Potions", "Потионы", "Potions");
        registerRaw("Cooldowns", "Кулдауны", "Cooldowns");
        registerRaw("Coords", "Координаты", "Coords");
        registerRaw("Inventory", "Инвентарь", "Inventory");
        registerRaw("Странный тип", "Странный тип", "Practice target");
        registerRaw("Джампики", "Джампики", "JumpCircle");
    }

    private ModLocalization() {
    }

    public static String tr(String key, Object... args) {
        String template = currentMap().getOrDefault(key, EN.getOrDefault(key, key));
        if (args == null || args.length == 0) {
            return template;
        }
        return String.format(Locale.ROOT, template, args);
    }

    public static String raw(String value) {
        if (value == null || value.isEmpty()) {
            return value == null ? "" : value;
        }
        return currentRawMap().getOrDefault(value, value);
    }

    private static Map<String, String> currentMap() {
        return currentLanguage() == GuiLanguage.RU ? RU : EN;
    }

    private static Map<String, String> currentRawMap() {
        return currentLanguage() == GuiLanguage.RU ? RU_RAW : EN_RAW;
    }

    private static GuiLanguage currentLanguage() {
        GuiLocalization.initialize();
        return GuiLocalization.currentLanguage();
    }

    private static void register(String key, String ruValue, String enValue) {
        RU.put(key, ruValue);
        EN.put(key, enValue);
    }

    private static void registerRaw(String rawValue, String ruValue, String enValue) {
        RU_RAW.put(rawValue, ruValue);
        EN_RAW.put(rawValue, enValue);
    }
}
